push to gcr

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -38,6 +38,14 @@ jobs:
           CR_TOKEN: "${{ secrets.HELM_RELEASE_TOKEN }}"
           CR_SKIP_EXISTING: "true"
 
-      - name: list files
+      - name: Push charts to GHCR
         run: |
-          tree -a
+          shopt -s nullglob
+          for pkg in .cr-release-packages/*; do
+            if [ -z "${pkg:-}" ]; then
+              break
+            fi
+            if ! helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts"; then
+              echo '::warning:: helm push failed!'
+            fi
+          done
